### ISSUE TITLE
Issue due to "param" value in launchfile

### ISSUE THREAD

**Issue by fcebron** [simchanu29/ros_simple_teleop#3]
When I'm launching the test launchfile (`roslaunch ros_teleop test.launch`) it works but I have the following error message (in red):

```
_[key_twist-3] process has died [pid 9642, exit code 1, cmd /home/MY_ACCOUNT/ros_ws/src/ros_teleop/src/key_interpreter.py __name:=key_twist __log:=/home/MY_ACCOUNT/.ros/log/04e288a6-6f18-11...3794434/key_twist-3.log].
log file: /home/MY_ACCOUNT/.ros/log/04e288a6-6f18-11...3794434/key_twist-3*.log
[key_int-4] process has died [pid 9643, exit code 1, cmd /home/MY_ACCOUNT/ros_ws/src/ros_teleop/src/key_interpreter.py __name:=key_int __log:=/home/MY_ACCOUNT/.ros/log/04e288a6-6f18-11...3794434/key_int-4.log].
log file: /home/MY_ACCOUNT/.ros/log/04e288a6-6f18-11...3794434/key_int-4*.log_
```

My terminal's complete output is the following one:

```
auto-starting new master
process[master]: started with pid [9611]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 04e288a6-6f18-11e8-80c6-d683d3794434
process[rosout-1]: started with pid [9624]
started core service [/rosout]
process[key_listener-2]: started with pid [9641]
process[key_twist-3]: started with pid [9642]
process[key_int-4]: started with pid [9643]
Traceback (most recent call last):
  File "/home/MY_ACCOUNT/ros_ws/src/ros_teleop/src/key_interpreter.py", line 39, in <module>
    topic_info = topic_map[topic_name]
KeyError: '/vel'
Traceback (most recent call last):
  File "/home/MY_ACCOUNT/ros_ws/src/ros_teleop/src/key_interpreter.py", line 39, in <module>
    topic_info = topic_map[topic_name]
KeyError: '/state'
[key_twist-3] process has died [pid 9642, exit code 1, cmd /home/MY_ACCOUNT/ros_ws/src/ros_teleop/src/key_interpreter.py __name:=key_twist __log:=/home/MY_ACCOUNT/.ros/log/04e288a6-6f18-11...3794434/key_twist-3.log].
log file: /home/MY_ACCOUNT/.ros/log/04e288a6-6f18-11...3794434/key_twist-3*.log
[key_int-4] process has died [pid 9643, exit code 1, cmd /home/MY_ACCOUNT/ros_ws/src/ros_teleop/src/key_interpreter.py __name:=key_int __log:=/home/MY_ACCOUNT/.ros/log/04e288a6-6f18-11...3794434/key_int-4.log].
log file: /home/MY_ACCOUNT/.ros/log/04e288a6-6f18-11...3794434/key_int-4*.log
```

So I have noticed that the value 'vel' and 'state' which generates the errors are in the 'test.launch' file (if you change them, this has an impact on the error message), but I don't understand why is it having this behaviour!

**Comment by fcebron** [comment]
I insist on the fact that it is working (I can echo the '/keys' topic)!

**Comment by simchanu29** [comment]
#3cfc83f should fix this issue
Thanks for the report

**Comment by fcebron** [comment]
You're welcome!

**Comment by fcebron** [comment]
I forgot to tell you that it's solved!
